"""#476 — Wave Function Collapse (Simple Tiled Model)

Procedural tiled-image generation via the Wave Function Collapse (WFC)
constraint-solver, after Maxim Gumin's "WaveFunctionCollapse"
(https://github.com/mxgmn/WaveFunctionCollapse, 2016). The simple/tiled
model was formalised by Gumin from the earlier texture-synthesis work of
Paul Merrell ("Model Synthesis", 2007) and the constraint-satisfaction view
of the Sudoku-style "wave" collapse by Karth et al.

What WFC does:
  • A grid of cells starts in a *superposition* — every cell may hold any of
    N tiles.
  • Tiles carry edge *sockets* (here: a connector present/absent on each of
    top/right/bottom/left). Two neighbouring tiles are compatible iff their
    touching sockets MATCH.
  • We repeatedly: (1) collapse the lowest-entropy cell to a single tile
    (weighted random), then (2) propagate the constraint to all neighbours
    (intersect their possible sets with the allowed tiles). Contradictions
    trigger a fresh restart with a new seed.
  • The final collapsed grid is a globally consistent tiling — pipe mazes,
    circuit boards, knot fields, labyrinths — that *looks* hand-authored
    but was generated by local adjacency rules only.

This is a CPU `@method` (Architecture A: the solver loop runs once and pushes
frames via `capture_frame`). The `evolve` animation captures the wave as it
collapses — collapsed cells show their tile, uncertain cells show an entropy
heatmap — so you literally watch the constraint solver converge. The
cumulative-sim Δ floor (pitfall #9) applies: verify via first-to-last-frame Δ,
not t=0 vs t=π, because consecutive collapse steps share most pixels.

Reference: https://github.com/mxgmn/WaveFunctionCollapse

Rule coverage:
  R1 PNG in every path (try/except + save fallback)  ·  R2 no temp files
  R3 @method kw-args + outputs=  ·  R4 write_scalars (tiles/entropy/contradictions)
  R5 write_field (tile-index map)  ·  R7 explicit imports  ·  R8 clean import
  R9 N/A (full-coverage RGB)  ·  R13 write_scalars(out_dir, **kwargs)
"""

from __future__ import annotations

import math
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw

from ...core.registry import method
from ...core.utils import (
    save, mn, seed_all, W, H, write_field, write_scalars, PALETTES,
)
from ...core.animation import capture_frame


# ── Tile sockets ─────────────────────────────────────────────────────
# A tile is (top, right, bottom, left) connectors; "1" = connector present,
# "0" = none. Adjacency: my TOP must equal neighbour-BOTTOM, etc.
_DIRS = ((0, -1), (1, 0), (0, 1), (-1, 0))  # top, right, bottom, left
# For direction d, which socket of *this* tile and of the *neighbour* must match
_SELF_SOCK = (0, 1, 2, 3)
_NEIGH_SOCK = (2, 3, 0, 1)  # neighbour's opposite socket


def _build_tileset(name: str) -> list[tuple[int, int, int, int]]:
    """Return the tile list (sockets) for a named tileset."""
    blank = (0, 0, 0, 0)
    line = [(1, 0, 1, 0), (0, 1, 0, 1)]                       # I-pieces (2)
    corner = [(1, 1, 0, 0), (0, 1, 1, 0), (0, 0, 1, 1), (1, 0, 0, 1)]  # L (4)
    tee = [(1, 1, 1, 0), (0, 1, 1, 1), (1, 0, 1, 1), (1, 1, 0, 1)]     # T (4)
    cross = (1, 1, 1, 1)
    if name == "labyrinth":
        return [*line, *corner, blank]          # no junctions → pure corridors
    if name in ("pipes", "circuit", "maze", "knots"):
        return [blank, cross, *line, *corner, *tee]
    return [blank, cross, *line, *corner, *tee]  # default


def _adjacency(tiles: list) -> list[list[int]]:
    """allowed[d][t] = bitmask of neighbour tiles compatible in direction d."""
    n = len(tiles)
    allowed = [[0] * n for _ in range(4)]
    for d in range(4):
        ss, ns = _SELF_SOCK[d], _NEIGH_SOCK[d]
        for t in range(n):
            mask = 0
            for u in range(n):
                if tiles[t][ss] == tiles[u][ns]:
                    mask |= (1 << u)
            allowed[d][t] = mask
    return allowed


def _popcount(x: int) -> int:
    return bin(x).count("1")


# ── Solver (returns grid of tile indices; -1 = contradiction) ────────
def _solve(cols: int, rows: int, tiles: list, allowed: list, rng) -> np.ndarray:
    n = len(tiles)
    full = (1 << n) - 1
    state = np.full((rows, cols), full, dtype=np.int64)

    def entropy_order():
        # cells with >1 option, min options first; tie-break random
        cands = []
        for y in range(rows):
            for x in range(cols):
                v = int(state[y, x])
                pc = _popcount(v)
                if pc > 1:
                    cands.append((pc, rng.random(), y, x))
        if not cands:
            return None
        cands.sort(key=lambda c: (c[0], c[1]))
        return cands[0][2], cands[0][3]

    for _step in range(cols * rows * 2 + 10):
        cell = entropy_order()
        if cell is None:
            break
        y, x = cell
        v = int(state[y, x])
        # pick a tile within the current superposition (weighted random)
        bits = [i for i in range(n) if v & (1 << i)]
        t = bits[rng.integers(0, len(bits))]
        state[y, x] = (1 << t)
        # propagate
        queue = [(y, x)]
        ok = True
        while queue and ok:
            cy, cx = queue.pop()
            cv = int(state[cy, cx])
            for d in range(4):
                ny, nx = cy + _DIRS[d][1], cx + _DIRS[d][0]
                if not (0 <= ny < rows and 0 <= nx < cols):
                    continue
                # allowed neighbour mask = union of allowed[d][t] for t in cv
                amask = 0
                tv = cv
                while tv:
                    lsb = tv & -tv
                    ti = (lsb.bit_length() - 1)
                    amask |= allowed[d][ti]
                    tv ^= lsb
                nv = int(state[ny, nx])
                inter = nv & amask
                if inter == 0:
                    ok = False
                    break
                if inter != nv:
                    state[ny, nx] = inter
                    queue.append((ny, nx))
        if not ok:
            return np.full((rows, cols), -1, dtype=np.int64)  # contradiction
    # any leftover superposed cell → collapse to first option
    grid = np.empty((rows, cols), dtype=np.int64)
    for y in range(rows):
        for x in range(cols):
            v = int(state[y, x])
            grid[y, x] = (v & -v).bit_length() - 1 if v else -1
    return grid


def _render_tile(sockets, tile_px: int, accent, bg, style: str) -> np.ndarray:
    """Render a single tile (sockets) to a (tile_px,tile_px,3) uint8 array."""
    img = Image.new("RGB", (tile_px, tile_px), tuple(int(c * 255) for c in bg))
    d = ImageDraw.Draw(img)
    c = tile_px / 2.0
    acc = tuple(int(c * 255) for c in accent)
    if style in ("pipes", "maze", "labyrinth"):
        lw = max(3, tile_px // 5)
        glow = max(2, lw // 2)
        for i, s in enumerate(sockets):
            if s:
                ox, oy = _DIRS[i]
                ex, ey = int(c + ox * c), int(c + oy * c)
                d.line([(c, c), (ex, ey)], fill=(acc[0]//2, acc[1]//2, acc[2]//2), width=lw + glow * 2)
        for i, s in enumerate(sockets):
            if s:
                ox, oy = _DIRS[i]
                ex, ey = int(c + ox * c), int(c + oy * c)
                d.line([(c, c), (ex, ey)], fill=acc, width=lw, joint="curve")
        if any(sockets):
            r = max(3, lw // 2 + 2)
            d.ellipse([c - r, c - r, c + r, c + r], fill=acc)
    elif style == "circuit":
        lw = max(2, tile_px // 8)
        for i, s in enumerate(sockets):
            if s:
                ox, oy = _DIRS[i]
                ex, ey = int(c + ox * c), int(c + oy * c)
                d.line([(c, c), (ex, ey)], fill=acc, width=lw)
        if sum(sockets) >= 2:
            r = max(3, tile_px // 7)
            d.ellipse([c - r, c - r, c + r, c + r], fill=acc)
    else:  # knots — smooth curves
        lw = max(3, tile_px // 6)
        for i, s in enumerate(sockets):
            if s:
                ox, oy = _DIRS[i]
                ex, ey = int(c + ox * c), int(c + oy * c)
                d.line([(c, c), (ex, ey)], fill=acc, width=lw, joint="curve")
    return np.asarray(img, dtype=np.uint8)


def _assemble(grid: np.ndarray, tiles: list, tile_px: int, accent, bg, style: str):
    rows, cols = grid.shape
    canvas = np.zeros((rows * tile_px, cols * tile_px, 3), dtype=np.uint8)
    for y in range(rows):
        for x in range(cols):
            t = int(grid[y, x])
            if t < 0:
                continue
            tile = _render_tile(tiles[t], tile_px, accent, bg, style)
            canvas[y * tile_px:(y + 1) * tile_px,
                   x * tile_px:(x + 1) * tile_px] = tile
    return canvas


def _resize(canvas: np.ndarray, w: int, h: int) -> np.ndarray:
    img = Image.fromarray(canvas)
    return np.asarray(img.resize((int(w), int(h)), Image.BILINEAR),
                      dtype=np.float32) / 255.0


@method(
    id="476",
    name="Wave Function Collapse",
    category="patterns",
    tags=["wfc", "procedural", "tiling", "constraint", "generation", "maze",
          "circuit", "knot", "emergence", "animation"],
    outputs={"image": "IMAGE", "field": "FIELD", "luminance": "SCALAR"},
    params={
        "tileset": {"description": "tile adjacency ruleset",
                    "choices": ["pipes", "circuit", "maze", "knots", "labyrinth"],
                    "default": "pipes"},
        "tile_size": {"description": "on-screen tile size in px (smaller = finer grid)",
                      "min": 16, "max": 80, "default": 28},
        "palette": {"description": "accent color palette", "default": "cool"},
        "bg_style": {"description": "background tone",
                     "choices": ["dark", "light"], "default": "dark"},
        "max_restarts": {"description": "solver restarts on contradiction",
                         "min": 1, "max": 20, "default": 10},
        "anim_mode": {"description": "animation mode", "choices": ["none", "evolve"],
                      "default": "none"},
        "anim_speed": {"description": "animation speed multiplier",
                       "min": 0.1, "max": 5.0, "default": 1.0},
    },
)
def method_wave_function_collapse(out_dir: Path, seed: int, params=None):
    """Wave Function Collapse — constraint-solved tiling (Gumin 2016).

    Builds a globally consistent tile grid from purely local adjacency rules.
    The `evolve` mode records the solver collapsing the wave (collapsed cells
    render as tiles, uncertain cells show an entropy heatmap), so the
    constraint propagation is visible frame-by-frame.

    Args:
        out_dir: output directory
        seed: random seed (deterministic solve)
        params: tileset, tile_size, palette, bg_style, max_restarts,
                anim_mode, anim_speed
    """
    try:
        if params is None:
            params = {}
        anim_mode = str(params.get("anim_mode", "none"))
        seed_all(seed)

        tileset = str(params.get("tileset", "pipes"))
        if tileset not in ("pipes", "circuit", "maze", "knots", "labyrinth"):
            tileset = "pipes"
        tile_size = int(params.get("tile_size", 28))
        tile_size = max(16, min(80, tile_size))
        pal_name = str(params.get("palette", "cool"))
        bg_style = str(params.get("bg_style", "dark"))
        max_restarts = int(params.get("max_restarts", 10))
        max_restarts = max(1, min(20, max_restarts))

        pal = PALETTES.get(pal_name, PALETTES["cool"])
        # Brightest palette entry on dark bg, darkest on light bg → high contrast.
        if bg_style == "light":
            bg = (0.93, 0.94, 0.97)
            accent = tuple(float(c) / 255.0 for c in pal[min(1, len(pal) - 1)])
        else:
            bg = (0.05, 0.06, 0.10)
            accent = tuple(float(c) / 255.0 for c in pal[-1])

        w, h = int(W), int(H)
        cols = max(4, w // tile_size)
        rows = max(4, h // tile_size)
        tiles = _build_tileset(tileset)
        allowed = _adjacency(tiles)
        n = len(tiles)
        tile_px = max(8, tile_size)

        rng = np.random.default_rng(seed)
        grid = None
        contradictions = 0
        for attempt in range(max_restarts):
            g = _solve(cols, rows, tiles, allowed, rng)
            if g.min() >= 0:
                grid = g
                break
            contradictions += 1
        if grid is None:
            grid = np.zeros((rows, cols), dtype=np.int64)  # blank fallback

        # ── Render final solved image ──
        canvas = _assemble(grid, tiles, tile_px, accent, bg, tileset)
        img = _resize(canvas, w, h)

        # FIELD = normalised tile-index map (downstream density/selectivity)
        field = grid.astype(np.float32) / max(1, n - 1)

        # ── Animation: capture the wave collapsing ──
        evolve = anim_mode == "evolve"
        if evolve:
            rng2 = np.random.default_rng(seed + 777)
            _capture_evolve(cols, rows, tiles, allowed, n, tile_px, accent, bg,
                            tileset, w, h, rng2, seed)

        save(img, mn(476, "Wave Function Collapse"), out_dir)
        try:
            write_field(out_dir, field)
            write_scalars(out_dir, tiles=float(n), grid_cols=float(cols),
                          grid_rows=float(rows),
                          contradictions=float(contradictions),
                          tileset_entropy=float(math.log2(n)))
        except Exception:
            pass
        return {"image": img, "field": field, "luminance": float(field.mean())}
    except Exception as exc:
        import traceback as _tb
        _tb.print_exc()
        fb = np.full((int(H), int(W), 3), 0.5, dtype=np.float32)
        save(fb, mn(476, "Wave Function Collapse"), out_dir)
        print(f"[method_476] ERROR: {exc}")
        return fb


def _capture_evolve(cols, rows, tiles, allowed, n, tile_px, accent, bg,
                    style, w, h, rng, seed):
    """Run a fresh solve while capturing intermediate wave states as frames.

    Collapsed cells render as tiles; still-superposed cells render as a gray
    entropy heatmap. Captures ~40 frames across the collapse so the solver's
    convergence is visible (Architecture A, cumulative-sim Δ floor applies).
    """
    full = (1 << n) - 1
    state = np.full((rows, cols), full, dtype=np.int64)
    frames_target = 40
    total_cells = cols * rows

    def entropy_order():
        cands = []
        for y in range(rows):
            for x in range(cols):
                v = int(state[y, x])
                pc = _popcount(v)
                if pc > 1:
                    cands.append((pc, rng.random(), y, x))
        if not cands:
            return None
        cands.sort(key=lambda c: (c[0], c[1]))
        return cands[0][2], cands[0][3]

    captured = 0
    step = 0
    while True:
        cell = entropy_order()
        if cell is None:
            break
        y, x = cell
        v = int(state[y, x])
        bits = [i for i in range(n) if v & (1 << i)]
        t = bits[rng.integers(0, len(bits))]
        state[y, x] = (1 << t)
        # propagate
        queue = [(y, x)]
        ok = True
        while queue and ok:
            cy, cx = queue.pop()
            cv = int(state[cy, cx])
            for d in range(4):
                ny, nx = cy + _DIRS[d][1], cx + _DIRS[d][0]
                if not (0 <= ny < rows and 0 <= nx < cols):
                    continue
                amask = 0
                tv = cv
                while tv:
                    lsb = tv & -tv
                    ti = lsb.bit_length() - 1
                    amask |= allowed[d][ti]
                    tv ^= lsb
                nv = int(state[ny, nx])
                inter = nv & amask
                if inter == 0:
                    ok = False
                    break
                if inter != nv:
                    state[ny, nx] = inter
                    queue.append((ny, nx))
        if not ok:
            # restart this animation solve cleanly
            state = np.full((rows, cols), full, dtype=np.int64)
            continue
        step += 1
        # capture roughly frames_target frames spread across the collapse
        if step % max(1, total_cells // frames_target) == 0 and captured < frames_target:
            grid = np.empty((rows, cols), dtype=np.int64)
            for yy in range(rows):
                for xx in range(cols):
                    vv = int(state[yy, xx])
                    grid[yy, xx] = (vv & -vv).bit_length() - 1 if vv else -1
            frame = _render_wave_state(state, grid, tiles, tile_px, accent, bg,
                                        style, w, h)
            capture_frame("476", frame)
            captured += 1
    # final fully-collapsed frame
    grid = np.empty((rows, cols), dtype=np.int64)
    for yy in range(rows):
        for xx in range(cols):
            vv = int(state[yy, xx])
            grid[yy, xx] = (vv & -vv).bit_length() - 1 if vv else -1
    frame = _resize(_assemble(grid, tiles, tile_px, accent, bg, style), w, h)
    capture_frame("476", frame)


def _render_wave_state(state, grid, tiles, tile_px, accent, bg, style, w, h):
    rows, cols = grid.shape
    canvas = np.zeros((rows * tile_px, cols * tile_px, 3), dtype=np.uint8)
    n = len(tiles)
    for y in range(rows):
        for x in range(cols):
            v = int(state[y, x])
            pc = _popcount(v)
            if pc == 1:
                t = (v & -v).bit_length() - 1
                tile = _render_tile(tiles[t], tile_px, accent, bg, style)
                canvas[y * tile_px:(y + 1) * tile_px,
                       x * tile_px:(x + 1) * tile_px] = tile
            else:
                # entropy heatmap: more options = brighter gray
                e = (pc - 1) / max(1, n - 1)
                gv = int(40 + 120 * e)
                canvas[y * tile_px:(y + 1) * tile_px,
                       x * tile_px:(x + 1) * tile_px] = (gv, gv, gv)
    return _resize(canvas, w, h)
