"""Math art methods — Ulam Spiral, Maze, Circle Packing, etc."""
from . import ulam_spiral
from . import maze
from . import lowpoly
from . import binary_counter
from . import circle_packing
from . import chaotic_map
from . import waveform
from . import fft_art
from . import density_heatmap
from . import fourier_circles
from . import dataviz
from . import strange_attractors
from . import spherical_harmonics
from . import polytope_4d
from . import domain_coloring
from . import marching_squares_contours
from . import fast_marching_geodesic
from . import space_colonization
