from __future__ import annotations

import math
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw

from ...core.registry import method
from ...core.utils import (
    save, mn, seed_all, W, H,
    write_scalars, write_field, write_mask, wired_source_lum,
)
from ...core.animation import capture_frame


# ── Poincaré disk {p,q} hyperbolic tessellation ──────────────────────────────
# Reference: H.S.M. Coxeter, "The Beauty of Geometry: Twelve Essays" (1999),
# essay "Angels and Devils" — the {p,q} regular tessellation of the hyperbolic
# plane represented in the Poincaré disk model. Also: Douglas Dunham's
# "Hyperbolic Tessellations" rendering notes (U. Minnesota Duluth).
#
# The hyperbolic plane (curvature -1) is mapped onto the open unit disk. A
# "line" (geodesic) is either a diameter or an arc of a circle orthogonal to
# the unit circle. The {p,q} tiling is the orbit of a regular p-gon under the
# reflection group generated by reflecting that p-gon in each of its sides;
# exactly q p-gons meet at every vertex. For (p-2)(q-2) > 4 the geometry is
# hyperbolic (Escher's "Circle Limit" regime).
#
# We build the fundamental {p,q} p-gon from its hyperbolic circumradius (closed
# form from the right-triangle at the polygon centre), then mirror it across
# each edge (a hyperbolic reflection — an isometry of the disk) doing a
# breadth-first flood that de-dups copies by centroid, terminating near the disk
# boundary. Each tile face is filled by BFS ring-depth and every geodesic edge
# is stroked as ink — the classic Escher line-art look.
#
# Architecture B (per-frame re-call): one frame per animation phase `t`. The
# CPU path is authoritative. `time` is in the schema; `none` mode is forced
# static (geometry independent of the clock) so it is a valid baseline.


def _valid_pq(p: int, q: int):
    """Push (p,q) into the hyperbolic regime (p-2)*(q-2) > 4 if needed."""
    p = max(3, int(p))
    q = max(3, int(q))
    guard = 0
    while (p - 2) * (q - 2) <= 4 and guard < 60:
        q += 1
        if q > 40:
            q = 3
            p += 1
        guard += 1
    return p, q


def _geodesic(e1: complex, e2: complex):
    """Return the geodesic through e1,e2 as ('d', angle) or ('c', cx, cy, R).

    A geodesic is a diameter (line through the origin) when the chord e1-e2
    passes through the origin, otherwise a circle orthogonal to the unit
    circle. Orthogonality gives |c|^2 = R^2 + 1, solved together with
    'passes through e1,e2' via the perpendicular-bisector intersection.
    """
    # Diameter test: e1 and e2 share a line through the origin.
    if abs(np.imag(np.conj(e1) * e2)) < 1e-9 * (abs(e1) * abs(e2) + 1e-9):
        return ("d", float(np.angle(e1)))
    m = (e1 + e2) * 0.5
    d = e2 - e1
    denom = 2.0 * np.imag(m * np.conj(d))
    if abs(denom) < 1e-12:
        return ("d", float(np.angle(e1)))
    # |c|^2 - |c - e1|^2 = 1  with  c = m + t * (i*d)
    t = (1.0 - abs(m) ** 2 + abs(d) ** 2 / 4.0) / denom
    u = 1j * d
    c = m + t * u
    R = abs(c - e1)
    if not np.isfinite(R) or R < 1e-6:
        return ("d", float(np.angle(e1)))
    return ("c", float(c.real), float(c.imag), float(R))


def _reflect_pt(z: complex, g):
    """Reflect point z across geodesic g (hyperbolic isometry of the disk)."""
    if g[0] == "d":
        return np.conj(z) * np.exp(2j * g[1])
    cx, cy, R = g[1], g[2], g[3]
    c = cx + 1j * cy
    zc = z - c
    return c + R * R * zc / (abs(zc) ** 2)


def _make_poly(V, p):
    edges = [_geodesic(V[k], V[(k + 1) % p]) for k in range(p)]
    cen = sum(V) / len(V)
    return {"V": V, "edges": edges, "cen": cen}


def _gen_tiling(p, q, max_polys, cutoff):
    """BFS-flood reflected p-gons from the central one. Returns list of polys."""
    # Hyperbolic right triangle at the polygon centre: A=pi/p, B=pi/q, C=pi/2.
    #   cosh(r_circum) = cot(A) * cot(B)
    A = math.pi / p
    B = math.pi / q
    cosh_rhoc = (math.cos(A) / math.sin(A)) * (math.cos(B) / math.sin(B))
    cosh_rhoc = max(cosh_rhoc, 1.0001)
    rhoc = math.acosh(cosh_rhoc)
    rc_euc = math.tanh(rhoc / 2.0)  # Euclidean circumradius in the disk

    V0 = [rc_euc * np.exp(1j * 2.0 * math.pi * k / p) for k in range(p)]
    central = _make_poly(V0, p)

    polys = []
    stack = [central]
    seen = {(_r3(central["cen"].real), _r3(central["cen"].imag))}
    while stack and len(polys) < max_polys:
        P = stack.pop()
        polys.append(P)
        for k in range(p):
            e1 = P["V"][k]
            e2 = P["V"][(k + 1) % p]
            g = _geodesic(e1, e2)
            Vn = [_reflect_pt(v, g) for v in P["V"]]
            Pn = _make_poly(Vn, p)
            if abs(Pn["cen"]) > cutoff:
                continue
            key = (_r3(Pn["cen"].real), _r3(Pn["cen"].imag))
            if key in seen:
                continue
            seen.add(key)
            stack.append(Pn)
    return polys


def _r3(x):
    return round(float(x), 3)


def _r4(x):
    return round(float(x), 4)


def _palette(t: float):
    """Inigo-Quilez cosine palette — smooth, periodic, vivid."""
    t = float(np.clip(t, 0.0, 1.0))
    r = 0.5 + 0.5 * math.cos(6.2831853 * (t + 0.00))
    g = 0.5 + 0.5 * math.cos(6.2831853 * (t + 0.33))
    b = 0.5 + 0.5 * math.cos(6.2831853 * (t + 0.67))
    return (r, g, b)


def _edge_pixels(a, b, g, cx, cy, s):
    """Sample the geodesic arc between a and b into pixel (x,y) points."""
    if g[0] == "d":
        n = max(2, int(math.hypot(a.real - b.real, a.imag - b.imag) * s * 2))
        ts = np.linspace(0.0, 1.0, n)
        pts_c = a + (b - a) * ts
    else:
        c = g[1] + 1j * g[2]
        R = g[3]
        a1 = np.angle(a - c)
        a2 = np.angle(b - c)
        d = a2 - a1
        while d > math.pi:
            d -= 2 * math.pi
        while d < -math.pi:
            d += 2 * math.pi
        n = max(2, int(abs(d) * R * s * 2))
        ang = a1 + np.linspace(0.0, d, n)
        pts_c = c + R * np.exp(1j * ang)
    xs = (cx + pts_c.real * s)
    ys = (cy - pts_c.imag * s)
    return [(float(x), float(y)) for x, y in zip(xs, ys)]


@method(id='452', name='Poincaré Tessellation', category='math_art', new_image_contract=True, tags=['hyperbolic', 'tessellation', 'poincare', 'escher', 'coxeter', 'geometry', 'tiling', 'expanded', 'animation'], inputs={'image_in': 'IMAGE'}, outputs={'image': 'IMAGE', 'mask': 'MASK'}, params={'p': {'description': 'sides of each central polygon (3-12)', 'min': 3, 'max': 12, 'default': 7}, 'q': {'description': 'polygons meeting at each vertex (3-12)', 'min': 3, 'max': 12, 'default': 3}, 'detail': {'description': 'max polygons flooded (tiling density)', 'min': 100, 'max': 2500, 'default': 900}, 'color_mode': {'description': 'face colour: depth (palette by ring), duo (two-tone), mono (paper)', 'choices': ['depth', 'duo', 'mono'], 'default': 'depth'}, 'bg': {'description': 'background outside the disk: space (dark), paper (light)', 'choices': ['space', 'paper'], 'default': 'space'}, 'line_width': {'description': 'edge stroke width (px)', 'min': 1.0, 'max': 4.0, 'default': 1.5}, 'anim_mode': {'description': 'animation mode: none, rotate (rigid spin), breathe (hyperbolic zoom)', 'choices': ['none', 'rotate', 'breathe'], 'default': 'none'}, 'anim_speed': {'description': 'animation speed multiplier', 'min': 0.1, 'max': 5.0, 'default': 1.0}, 'time': {'description': 'animation time in radians', 'min': 0.0, 'max': 6.2832, 'default': 0.0}, 'source': {'description': 'wired upstream image as a domain-warp / seed source', 'choices': ['none', 'input_image'], 'default': 'none'}})
def method_poincare_tessellation(out_dir: Path, seed: int, params=None):
    """Poincaré disk {p,q} hyperbolic tessellation (Coxeter / Escher).

    Renders the regular {p,q} tessellation of the hyperbolic plane in the
    Poincaré disk model. A regular p-gon (q meeting at each vertex) is placed at
    the centre; its geodesic edges are circles orthogonal to the unit circle.
    The whole tiling is generated by repeatedly reflecting that p-gon across
    each of its sides (a hyperbolic reflection — an isometry of the disk), with
    copy de-duplication by centroid, flooding outward until the disk boundary.

    Face colour encodes BFS ring-depth from the centre (the classic nested
    "Circle Limit" palette); every geodesic edge is stroked as ink. The output
    is the full disk (RGB), with a solid background outside it.

    Animation (Architecture B — one frame per phase ``t``):
      none    - static baseline (geometry ignores the clock)
      rotate  - rigid Möbius rotation about the centre (isometry: the tiling
                sweeps through distinct phases, returning every 2*pi/p)
      breathe - radial hyperbolic zoom (z *= scale) producing an in/out pulse

    CPU path authoritative. Per-frame cost stays under budget because each frame
    re-rasterizes from the cached tiling geometry (stroke + fill, ~hundreds of
    polygons).

    Params:
        p:          sides of each central polygon (3-12)
        q:          polygons meeting at each vertex (3-12)
        detail:     max polygons flooded (100-2500)
        color_mode: depth (palette by ring) / duo (two-tone) / mono (paper)
        bg:         space (dark) / paper (light) outside the disk
        line_width: edge stroke width (1-4 px)
        time:       animation clock (0-6.28)
        anim_mode:  none / rotate / breathe
        anim_speed: animation speed (0.1-5)
    """
    try:
        if params is None:
            params = {}
        anim_time = float(params.get("time", 0.0))
        anim_mode = str(params.get("anim_mode", "none"))
        anim_speed = float(params.get("anim_speed", 1.0))
        seed_all(seed)
        rng = np.random.default_rng(seed)

        p = int(np.clip(params.get("p", 7), 3, 12))
        q = int(np.clip(params.get("q", 3), 3, 12))
        p, q = _valid_pq(p, q)
        detail = int(np.clip(params.get("detail", 900), 100, 2500))
        # Animated frames cap polygon count for speed; static keeps full detail.
        max_polys = detail if anim_mode == "none" else min(detail, 400)
        color_mode = str(params.get("color_mode", "depth"))
        bg_mode = str(params.get("bg", "space"))
        lw = float(np.clip(params.get("line_width", 1.5), 1.0, 4.0))

        # none mode must be static regardless of the passed clock
        _t = 0.0 if anim_mode == "none" else anim_time * anim_speed

        h = int(H)
        w = int(W)
        cx = w / 2.0
        cy = h / 2.0
        s = 0.49 * min(w, h)

        # ── Build the tiling (Euclidean-disk complex coords) ──
        polys = _gen_tiling(p, q, max_polys, cutoff=0.985)
        max_depth = max(1, len(polys) - 1)

        # ── Animation transforms (applied to every vertex) ──
        if anim_mode == "rotate":
            rot = np.exp(1j * _t)
        else:
            rot = 1.0 + 0.0j
        if anim_mode == "breathe":
            scale = 1.0 + 0.18 * math.sin(_t)
        else:
            scale = 1.0

        def xform(z: complex) -> complex:
            return (z * rot) * scale

        # ── Background ──
        if bg_mode == "paper":
            bg = np.array([0.96, 0.945, 0.91], dtype=np.float32)
        else:
            bg = np.array([0.04, 0.045, 0.08], dtype=np.float32)
        canvas = np.tile(bg, (h, w, 1)).astype(np.float32)

        # ── Face fill (always) ──
        filled = np.full((h, w), -1, dtype=np.int32)
        depth_field = np.zeros((h, w), dtype=np.float32)
        for idx, P in enumerate(polys):
            Vt = [xform(v) for v in P["V"]]
            cen = sum(Vt) / len(Vt)
            xs = [cx + (v.real) * s for v in Vt]
            ys = [cy - (v.imag) * s for v in Vt]
            x0 = int(max(0, math.floor(min(xs))))
            x1 = int(min(w - 1, math.ceil(max(xs))))
            y0 = int(max(0, math.floor(min(ys))))
            y1 = int(min(h - 1, math.ceil(max(ys))))
            if x1 < x0 or y1 < y0:
                continue
            sub = filled[y0:y1 + 1, x0:x1 + 1]
            if int(sub.min()) >= 0:
                continue  # bbox already fully painted
            xx, yy = np.meshgrid(
                np.arange(x0, x1 + 1), np.arange(y0, y1 + 1), indexing="xy"
            )
            Z = (xx - cx) / s + 1j * (cy - yy) / s
            inside = np.ones(Z.shape, dtype=bool)
            for eg in P["edges"]:
                if eg[0] == "d":
                    sgn = np.imag(Z * np.exp(-1j * eg[1]))
                    s0 = np.imag(cen * np.exp(-1j * eg[1]))
                else:
                    c = eg[1] + 1j * eg[2]
                    sgn = np.abs(Z - c) - eg[3]
                    s0 = abs(cen - c) - eg[3]
                inside = inside & (np.sign(sgn) == np.sign(s0))
            unfilled = sub < 0
            m = inside & unfilled
            if not m.any():
                continue
            if color_mode == "mono":
                col = np.array([0.93, 0.92, 0.88], dtype=np.float32)
            elif color_mode == "duo":
                col = (np.array([0.10, 0.12, 0.22], dtype=np.float32)
                       if (idx % 2) else np.array([0.85, 0.80, 0.55], dtype=np.float32))
            else:  # depth
                col = np.array(_palette(idx / max_depth), dtype=np.float32)
            sub[m] = idx
            depth_field[y0:y0 + m.shape[0], x0:x0 + m.shape[1]][m] = idx / max_depth
            yyv, xxv = np.nonzero(m)
            canvas[y0 + yyv, x0 + xxv] = col

        # ── Edge strokes (all frames) ──
        ink_rgb = (10, 10, 18) if bg_mode == "space" else (20, 18, 30)
        stroke_img = Image.new("RGBA", (w, h), (0, 0, 0, 0))
        draw = ImageDraw.Draw(stroke_img)
        seen_edges = set()
        lw_px = max(1, int(round(lw)))
        for P in polys:
            Vt = [xform(v) for v in P["V"]]
            for k in range(p):
                a = Vt[k]
                b = Vt[(k + 1) % p]
                key = (_r4(a.real), _r4(a.imag), _r4(b.real), _r4(b.imag))
                if key in seen_edges:
                    continue
                seen_edges.add(key)
                pts = _edge_pixels(a, b, _geodesic(a, b), cx, cy, s)
                if len(pts) >= 2:
                    draw.line(pts, fill=ink_rgb + (255,), width=lw_px, joint="curve")

        stroke = np.array(stroke_img, dtype=np.float32) / 255.0
        sa = stroke[:, :, 3:4]
        canvas = canvas * (1.0 - sa) + stroke[:, :, :3] * sa
        canvas = np.clip(canvas, 0.0, 1.0).astype(np.float32)

        # ── Mask: filled = ring-depth over the disk ──
        mask = (filled >= 0).astype(np.float32) * (0.4 + 0.6 * depth_field)

        # ── Sidecar outputs (Rule 4 & 5) ──
        write_field(out_dir, depth_field.astype(np.float32))
        write_scalars(out_dir, p=float(p), q=float(q),
                      n_polygons=float(len(polys)), max_depth=float(max_depth))
        write_mask(out_dir, mask.astype(np.float32))

        capture_frame("452", canvas)
        save(canvas, mn(452, f"Poincaré Tessellation t={_t:.2f}"), out_dir)
        return canvas
    except Exception as exc:
        fallback = np.zeros((int(H), int(W), 3), dtype=np.float32) + \
            np.array([0.04, 0.045, 0.08], dtype=np.float32)
        save(fallback, mn(452, "Poincaré Tessellation"), out_dir)
        print(f"[method_452] ERROR: {exc}")
        return fallback
