#!/usr/bin/env python3
"""Precompute 6D shape vectors for all printable ASCII characters.

Each character's 6D shape vector captures its visual density across 6 staggered
circular regions of the monospace cell. These vectors are used by the GPU ASCII
shader for shape-based nearest-neighbor character selection.

Output: C-style const float array suitable for embedding in GLSL.

Usage:
    python image_pipeline/tools/precompute_ascii_shape_vectors.py

The generated GLSL code is printed to stdout. Copy it into the ascii_art_gpu shader.
"""

from __future__ import annotations
import math
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

# ── Configuration ───────────────────────────────────────────────────
# Cell dimensions (in pixels) for shape vector precomputation.
# Must match a monospace font aspect ratio (~2:1 height:width for default).
CELL_W = 20
CELL_H = 40
FONT_SIZE = 32  # larger than cell so glyph fills it

# 6 staggered sampling circles (normalized 0..1 within cell)
# 2 columns × 3 rows, staggered vertically for coverage
SAMPLING_CIRCLES = [
    (0.20, 0.17),   # 0: top-left
    (0.80, 0.17),   # 1: top-right
    (0.17, 0.40),   # 2: mid-left
    (0.83, 0.40),   # 3: mid-right
    (0.20, 0.72),   # 4: bottom-left
    (0.80, 0.72),   # 5: bottom-right
]
CIRCLE_RADIUS_FRAC = 0.18  # as fraction of cell width


def load_font(size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    """Load a monospace font with good ASCII coverage."""
    candidates = [
        "/System/Library/Fonts/Menlo.ttc",
        "/System/Library/Fonts/Courier.dfont",
        "/System/Library/Fonts/Andale Mono.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
    ]
    for p in candidates:
        pp = Path(p)
        if pp.exists():
            try:
                return ImageFont.truetype(str(pp), size)
            except Exception:
                continue
    # Fallback
    return ImageFont.load_default()


def compute_shape_vector(char: str, font, cell_w: int, cell_h: int) -> list[float]:
    """Compute 6D shape vector by measuring pixel coverage in 6 staggered circles."""
    # Render character into a cell-sized image (white on black)
    img = Image.new("L", (cell_w, cell_h), 0)
    draw = ImageDraw.Draw(img)
    try:
        bbox = draw.textbbox((0, 0), char, font=font)
        tw = bbox[2] - bbox[0]
        th = bbox[3] - bbox[1]
    except (AttributeError, TypeError):
        tw, th = font.getsize(char)
    ox = (cell_w - tw) // 2 - bbox[0]  # centering
    oy = (cell_h - th) // 2 - bbox[1]
    draw.text((ox, oy), char, fill=255, font=font)
    pix = img.load()
    if pix is None:
        return [0.0] * len(SAMPLING_CIRCLES)

    cell_center = (cell_w / 2, cell_h / 2)
    rad = CIRCLE_RADIUS_FRAC * cell_w
    rad2 = rad * rad

    vectors = []
    for (cx_norm, cy_norm) in SAMPLING_CIRCLES:
        cx = cx_norm * cell_w
        cy = cy_norm * cell_h
        # Sample pixels within the circle
        total = 0
        hits = 0
        # Bounding box of circle
        bx0 = max(0, int(cx - rad))
        bx1 = min(cell_w, int(cx + rad) + 1)
        by0 = max(0, int(cy - rad))
        by1 = min(cell_h, int(cy + rad) + 1)
        for py in range(by0, by1):
            dy = py - cy
            dy2 = dy * dy
            for px in range(bx0, bx1):
                dx = px - cx
                if dx * dx + dy2 <= rad2:
                    total += 1
                    if pix[px, py] > 128:
                        hits += 1
        value = hits / max(total, 1)
        vectors.append(value)

    return vectors


def normalize_vectors(all_vectors: list[list[float]]) -> list[list[float]]:
    """Normalize each dimension to [0, 1] across all characters."""
    dims = len(SAMPLING_CIRCLES)
    max_vals = [0.0] * dims
    for vec in all_vectors:
        for i in range(dims):
            if vec[i] > max_vals[i]:
                max_vals[i] = vec[i]

    # Ensure no division by zero
    for i in range(dims):
        if max_vals[i] < 1e-10:
            max_vals[i] = 1.0

    normalized = []
    for vec in all_vectors:
        normalized.append([vec[i] / max_vals[i] for i in range(dims)])
    return normalized


def generate_glsl_array(chars: list[str], vectors: list[list[float]]) -> str:
    """Generate flat 1D GLSL const float array code for the shape vectors.

    Flattened to 1D for GLSL 330 compatibility:
      index = char_idx * dims + dim_idx
    """
    dims = len(SAMPLING_CIRCLES)
    count = len(chars)

    lines = [
        f"// Precomputed {dims}D shape vectors for {count} ASCII characters (flat 1D)",
        f"// Generated by precompute_ascii_shape_vectors.py",
        f"// Cell size: {CELL_W}x{CELL_H}, circle radius: {CIRCLE_RADIUS_FRAC:.2f}×cell_w",
        f"// Staggered 2×3 sampling circles: {SAMPLING_CIRCLES}",
        f"#define ASCII_CHAR_COUNT {count}",
        f"#define ASCII_VEC_DIMS {dims}",
        "",
        f"// Access: ASCII_SHAPE_VECTORS[char_idx * {dims} + dim_idx]",
        f"const float ASCII_SHAPE_VECTORS[{count * dims}] = float[{count * dims}](",
    ]

    # Group for readable output (~6 values per line)
    for idx, (ch, vec) in enumerate(zip(chars, vectors)):
        # Only show comment on first line of each character
        safe_ch = repr(ch)[1:-1] if ch != "'" else "'"
        all_vals = [f"{v:.6f}" for v in vec]
        lines.append(f"    {', '.join(all_vals)}, // {idx:3d} '{safe_ch}'")

    lines.append(");")
    return "\n".join(lines)


def generate_ascii_character_list() -> tuple[list[str], str]:
    """Return printable ASCII characters and a GLSL char-code array.

    Returns (chars, glsl_code) where chars is the list of character strings
    and glsl_code is the const int array mapping index → char code.
    """
    chars = [chr(i) for i in range(32, 127)]  # space through ~
    count = len(chars)
    lines = [
        f"// ASCII character codes {count} chars (32=' ' .. 126='~')",
        f"const int ASCII_CHAR_CODES[{count}] = int[{count}](",
    ]
    for idx, ch in enumerate(chars):
        comma = "," if idx < count - 1 else ""
        lines.append(f"    {ord(ch)}{comma} // {idx:3d} '{ch}'")
    lines.append(");")
    return chars, "\n".join(lines)


def main():
    font = load_font(FONT_SIZE)
    chars, _ = generate_ascii_character_list()

    # ASCII character codes list with proper comma placement
    print("// ASCII character codes 95 chars (32=' ' .. 126='~')")
    print("const int ASCII_CHAR_CODES[95] = int[95](")
    for idx, ch in enumerate(chars):
        comma = "," if idx < 94 else ""
        print(f"    {ord(ch)}{comma} // {idx:3d} '{ch}'")
    print(");")

    # Compute shape vectors
    all_vectors = []
    for ch in chars:
        vec = compute_shape_vector(ch, font, CELL_W, CELL_H)
        all_vectors.append(vec)

    # Normalize
    normalized = normalize_vectors(all_vectors)

    # Generate GLSL code — print AFTER the char codes and separator
    glsl = generate_glsl_array(chars, normalized)
    print()
    print(glsl)
    print()

    # Also print the external affecting indices map for the shader
    print("// Directional contrast enhancement: external→internal mapping")
    print("// Each internal index i lists which external indices affect it")
    affecting = [
        [0, 1, 2, 4],  # internal 0 (top-left) → affected by top + mid-right
        [0, 1, 3, 5],  # internal 1 (top-right) → affected by top + mid-left
        [2, 4, 6],     # internal 2 (mid-left) → affected by left + bottom-left
        [3, 5, 7],     # internal 3 (mid-right) → affected by right + bottom-right
        [4, 6, 8, 9],  # internal 4 (bottom-left) → affected by bottom + left
        [5, 7, 8, 9],  # internal 5 (bottom-right) → affected by bottom + right
    ]
    mapping_lines = ["// Flat 1D: index = internal_idx * 4 + entry_idx, padded with -1 for shorter rows"]
    max_affecting = max(len(a) for a in affecting)
    mapping_lines.append(f"const int AFFECTING_EXTERNAL[{len(affecting) * max_affecting}] = int[{len(affecting) * max_affecting}](")
    for i, affecting_list in enumerate(affecting):
        padded = affecting_list + [-1] * (max_affecting - len(affecting_list))
        vals = ", ".join(str(a) for a in padded)
        comma = "," if i < len(affecting) - 1 else ""
        mapping_lines.append(f"    {vals}{comma} // internal {i}")
    mapping_lines.append(");")
    mapping_lines.append(f"#define MAX_AFFECTING {max_affecting}")
    print("\n".join(mapping_lines))
    print()

    # Print staggered sampling circle positions (normalized within cell)
    print("// Internal sampling circle positions (fractional within cell)")
    print(f"const vec2 INTERNAL_SAMPLE_POS[{len(SAMPLING_CIRCLES)}] = vec2[{len(SAMPLING_CIRCLES)}](")
    for idx, (cx, cy) in enumerate(SAMPLING_CIRCLES):
        comma = "," if idx < len(SAMPLING_CIRCLES) - 1 else ""
        print(f"    vec2({cx:.3f}, {cy:.3f}){comma} // internal {idx}")
    print(");")

    # External sampling positions (outside cell, in cell-relative coords)
    # These positions are in UV offset space relative to the cell:
    # (0,0) = cell top-left, (1,1) = cell bottom-right
    # Positions < 0 or > 1 reach into neighboring cells
    external_positions = [
        (-0.15, -0.15),  # 0: top-left (outside)
        (0.50, -0.15),   # 1: top-center
        (1.15, -0.15),   # 2: top-right
        (-0.15, 0.50),   # 3: mid-left
        (1.15, 0.50),    # 4: mid-right
        (-0.15, 1.15),   # 5: bottom-left
        (0.50, 1.15),    # 6: bottom-center
        (1.15, 1.15),    # 7: bottom-right
        (-0.15, 0.85),   # 8: left-low
        (1.15, 0.85),    # 9: right-low
    ]
    print()
    print("// External sampling positions (offset from cell origin, can be outside [0,1])")
    print("const vec2 EXTERNAL_SAMPLE_POS[10] = vec2[10](")
    for idx, (ex, ey) in enumerate(external_positions):
        comma = "," if idx < 9 else ""
        print(f"    vec2({ex:.3f}, {ey:.3f}){comma} // external {idx}")
    print(");")


if __name__ == "__main__":
    main()
