#!/usr/bin/env python3
"""Bulk-precompute 6×8 glyph bitmaps for multiple monospace fonts.

Generates GLYPH_LO and GLYPH_HI arrays for each font, plus the font
name lookup table. Output is Python code for ascii_gpu_data.py.
"""
from __future__ import annotations
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

GLYPH_W = 6
GLYPH_H = 8
SCALE = 6
RENDER_W = GLYPH_W * SCALE
RENDER_H = GLYPH_H * SCALE
FONT_SIZE = 42
THRESHOLD = 0.35


# Font definitions: (name, path_or_paths, index)
# .ttc files can contain multiple fonts; index selects which one
FONTS: list[tuple[str, str | list[str], int]] = [
    ("menlo",   "/System/Library/Fonts/Menlo.ttc", 0),
    ("courier", "/System/Library/Fonts/Courier.ttc", 0),
    ("monaco",  "/System/Library/Fonts/Monaco.ttf", 0),
    ("sf-mono", "/System/Library/Fonts/SFNSMono.ttf", 0),
    ("andale",  "/System/Library/Fonts/Supplemental/Andale Mono.ttf", 0),
    ("courier-new", "/System/Library/Fonts/Supplemental/Courier New.ttf", 0),
]

FONT_NAMES = [f[0] for f in FONTS]


def render_bitmap(char: str, font, gw: int, gh: int, scale: int) -> int:
    """Render character, downscale to gw×gh, return packed bitmask."""
    rw = gw * scale
    rh = gh * scale
    img = Image.new("L", (rw, rh), 0)
    draw = ImageDraw.Draw(img)
    try:
        bbox = draw.textbbox((0, 0), char, font=font)
        tw = bbox[2] - bbox[0]
        th = bbox[3] - bbox[1]
    except (AttributeError, TypeError):
        tw, th = font.getsize(char)
        bbox = (0, 0, tw, th)
    ox = (rw - tw) // 2 - bbox[0]
    oy = (rh - th) // 2 - bbox[1]
    draw.text((ox, oy), char, fill=255, font=font)
    pix = img.load()
    if pix is None:
        return 0
    tval = int(THRESHOLD * 255)
    bits = 0
    for y in range(gh):
        for x in range(gw):
            sy = y * scale
            sx = x * scale
            total = 0
            for dy in range(scale):
                for dx in range(scale):
                    total += int(pix[sx + dx, sy + dy])
            if total // (scale * scale) > tval:
                bits |= 1 << (y * gw + x)
    return bits


def pack_pair(bits: int) -> tuple[int, int]:
    return (bits & 0xFFFFFFFF, (bits >> 32) & 0xFFFF)


def main():
    chars = [chr(i) for i in range(32, 127)]
    count = len(chars)
    nfonts = len(FONTS)

    print(f"# Auto-generated by {Path(__file__).name}")
    print(f"# {nfonts} fonts, {count} chars each, {GLYPH_W}×{GLYPH_H} glyphs")
    print(f"# Rendered at {RENDER_W}×{RENDER_H}, {SCALE}× downscale, threshold={THRESHOLD}")
    print()

    # Build GLYPH_LO/HI for all fonts as flat arrays
    all_lo: list[int] = []
    all_hi: list[int] = []
    font_summaries = []

    for fname, fpath, findex in FONTS:
        try:
            font = ImageFont.truetype(fpath, FONT_SIZE, index=findex)
        except Exception as e:
            print(f"// ERROR loading {fname}: {e}")
            print(f"// Using zero bitmaps for {fname}")
            all_lo.extend([0] * count)
            all_hi.extend([0] * count)
            font_summaries.append(f"  // {fname}: LOAD ERROR")
            continue

        unique = set()
        for idx in range(count):
            bits = render_bitmap(chars[idx], font, GLYPH_W, GLYPH_H, SCALE)
            lo, hi = pack_pair(bits)
            all_lo.append(lo)
            all_hi.append(hi)
            unique.add((lo, hi))

        collisions = count - len(unique)
        font_summaries.append(f"  // {fname}: {len(unique)}/{count} unique ({collisions} collisions)")

    # Print font names
    print("FONT_NAMES = [")
    for idx, name in enumerate(FONT_NAMES):
        comma = "," if idx < nfonts - 1 else ""
        print(f'    "{name}"{comma}')
    print("]")
    print()

    # Print summaries
    print("// Font bitmap stats:")
    for s in font_summaries:
        print(s)
    print()

    # Print GLYPH_LO
    total = nfonts * count
    print(f"# glyph_storage[font_idx * {count} + char_idx]")
    print(f"GLYPH_LO = [  # {total} entries, {nfonts} fonts × {count} chars")
    for fi in range(nfonts):
        print(f"    # -- {FONT_NAMES[fi]} --")
        for ci in range(count):
            lo = all_lo[fi * count + ci]
            comma = "," if fi < nfonts - 1 or ci < count - 1 else ""
            print(f"    {lo}{comma}  # {ci:3d} '{chars[ci]}'")
    print("]")
    print()

    print(f"GLYPH_HI = [  # {total} entries, {nfonts} fonts × {count} chars")
    for fi in range(nfonts):
        print(f"    # -- {FONT_NAMES[fi]} --")
        for ci in range(count):
            hi = all_hi[fi * count + ci]
            comma = "," if fi < nfonts - 1 or ci < count - 1 else ""
            print(f"    {hi}{comma}  # {ci:3d} '{chars[ci]}'")
    print("]")


if __name__ == "__main__":
    main()
