"""Simulations methods."""
from . import boids
from . import flowfield
from . import dla
from . import reaction_diffusion
from . import refractive_caustics
from . import metaballs
from . import sandpile
from . import random_walk
from . import particles
from . import langtons_ant
from . import quantum_interference
from . import physarum
from . import cyclic_ca
from . import particle_life
from . import kuramoto
from . import lenia
from . import bz_oregonator
from . import lattice_gas
from . import ising
from . import stadium_billiards
from . import wave_equation
from . import coupled_logistic
from . import lloyds_algorithm
from . import forest_fire
from . import sph
from . import active_nematic
from . import swarmalators
from . import viscous_fingering
from . import chaotic_pendulums
from . import magnetic_pendulum
from . import dielectric_breakdown
from . import rayleigh_taylor
from . import sheared_rayleigh_taylor
from . import multilayer_rt
from . import tesseract
from . import nbody_gravity
from . import cahn_hilliard
from . import lotka_volterra
from . import kelvin_helmholtz
from . import spring_mass_network
from . import point_vortex
from . import lv_turing
from . import lv_3species
from . import lv_anisotropic
from . import magnetic_reconnection
from . import lic_flow
from . import spatial_pd
from . import spd_replicator
from . import active_brownian
from . import nlse
from . import dendritic_solidification
from . import chladni
from . import shallow_water
from . import cellular_potts
from . import burridge_knopoff
from . import particle_painter
from . import complex_ginzburg_landau
from . import kuramoto_sivashinsky
from . import fitzhugh_nagumo
from . import gray_scott
from . import chemotaxis
from . import kpz_surface_growth
from . import elastic_coiling
from . import hydraulic_erosion
from . import bacterial_colony
from . import bacterial_colony_v2
from . import rayleigh_benard
from . import darcy_benard
from . import ac_darcy
from . import roessler_array
from . import fractional_rd
from . import faraday_waves
from . import spectral_tapestry
from . import coupled_map_lattice
from . import dynamic_fracture
from . import oscillon_resonance
from . import buckling_lattice
from . import ocean_spectral
from . import pm_anisotropic_rd
from . import gpe_vortex
from . import ferrofluid
from . import chua_lattice
from . import moire_animation
from . import turing_morphogenesis
from . import pfc
from . import sand_dune_migration
from . import space_colonization
from . import stable_fluids
from . import water_ripple
from . import lattice_boltzmann
from . import differential_growth