"""Auto-import all chord node modules. Each module registers its nodes into the registry."""
from . import (
    tonic,
    function,
    phrase,
    cadence,
    modulation,
    rest,
    pedal,
    tension_shaper,
    substitution,
    voice_leader,
    bass,
    arpeggiator,
    rhythm,
    color,
    secondary_dominant,
    sequence,
    suspension,
    passing_chord,
)
